EASY-1802 give write permission to group for deposits
DANS-KNAW/easy-deposit pull request #109
Opened 2018-11-26 13:13 UTC by stephanHogenboom

Fixes EASY-1802

#### When applied it will
* give write acces to the group
#### Where should the reviewer @DANS-KNAW/easy start?

#### How should this be manually tested?

try to modify/ delete a deposit and its content on  deasy/ teasy in the sword tmp folder

2018-11-26 13:33 UTC, rvanheest requested changes

2018-11-26 13:33 UTC, rvanheest commented on src/main/scala/nl.knaw.dans.easy.sword2/DepositHandler.scala
> +      FilesPermissionService.changePermissionsForDirectoryAndContent(tempDir, settings.depositPermissions, id).get
try to write this `Try` block as a for-comprehension. That way you loose the `.get`.

2018-11-26 13:33 UTC, rvanheest commented on src/test/scala/nl.knaw.dans.easy.sword2/FilePermissionServiceSpec.scala
> +    better.files.File(getClass.getResource("/input/").toURI).copyTo(inputDir)
normal import here, please

2018-11-26 13:33 UTC, rvanheest commented on src/test/scala/nl.knaw.dans.easy.sword2/FilePermissionServiceSpec.scala
> +
```suggestion
```

2018-11-26 14:40 UTC, rvanheest approved these changes

2018-11-27 08:52 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.easy.sword2/DepositHandler.scala
> +      _ <- FilesPermissionService.changePermissionsForDirectoryAndContent(deposit.getFile, settings.depositPermissions, id) // set file permissions after continued deposit is finished
I guess Util is more common in our team than Service. Service reminds too much of servers with servlets.

2018-11-27 08:52 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.easy.sword2/DepositHandler.scala
> +    FilesPermissionService.changePermissionsForDirectoryAndContent(depositDir, settings.depositPermissions, id)
changePermissionsRecursively?

2018-11-27 08:52 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.easy.sword2/FilesPermissionService.scala
> +  // previous classname MakeAllGroupWritable was deceptive as the argument (posix permission string) can be something else than rwxrwx---
This type of comment belongs in a commit message.

2018-11-27 08:52 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.easy.sword2/FilesPermissionService.scala
> +        case se: SecurityException => log.error(s"Not enough privileges to set file permissions on $path"); FileVisitResult.TERMINATE
For all 4:
either `case _: SecurityException` or 
```suggestion
        case se: SecurityException => log.error(s"Not enough privileges to set file permissions on $path",se); FileVisitResult.TERMINATE
```

2018-11-28 11:23 UTC, merged