EASY-1126 extend SWORD statement with the item-uri's of archived files
DANS-KNAW/easy-deposit pull request #74
Opened 2016-11-30 14:01 UTC by vesaakerman

fixes EASY-1126

#### When applied
* it will store the `bag-id` and `filepaths` of the deposited files in `deposit.properties` when the bag is deposited
* after the bag has been archived, it will add the` bag-id` and `filepaths` into the `AtomStatement` when the client enquires the deposit state  

#### Where should the reviewer @DANS-KNAW/easy start?

#### How should this be manually tested?
* deposit a bag (/send-simple.sh my/bag.zip http://deasy.dans.knaw.nl/sword2/collection/1)
* ask state (./get.sh  http://deasy.dans.knaw.nl/sword2/statement/mendeltest-...)

#### related pull requests on github
repo                       | PR                | note
-------------------------- | ----------------- | ----
easy-                      | [PR#](PRlink)     |

2016-11-30 14:22 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/api/sword2/StatementManagerImpl.scala
> +    val filePathsResources = resources.filePaths.map(resource => { val resourcePart = new ResourcePart(resource.trim); resourcePart.setMediaType("multipart/related;type=file"); resourcePart})
not entirely sure about this lambda... I don't think you need the `resourcePart`

2016-12-06 15:11 UTC, janvanmansum requested changes
Not quite right yet. Please, see comments.

2016-12-06 15:11 UTC, janvanmansum commented on src/main/scala/nl/knaw/dans/api/sword2/StatementManagerImpl.scala
> +    val filePathsResources = resources.filePaths.map(resource => { val resourcePart = new ResourcePart(resource.trim); resourcePart.setMediaType("multipart/related;type=file"); resourcePart})
At any rate, don' put everything on one line.

2016-12-06 15:11 UTC, janvanmansum commented on src/main/scala/nl/knaw/dans/api/sword2/DepositHandler.scala
> +      resources <- getResources(bag)
This was not the intention. `easy-ingest-flow` should set the resources when they are actually created in archival storage, not `easy-sword2`. At this point we cannot be sure that the archival copy has actually been created.

2016-12-06 15:11 UTC, janvanmansum commented on src/main/scala/nl/knaw/dans/api/sword2/package.scala
> +  case class PropertiesResources(bagId: String, filePaths: List[String])
Instead of bagId and filePaths it should be bagUri and fileUris. When sending an update, the client will include URIs in the `fetch.txt`.

2016-12-06 17:41 UTC, vesaakerman commented on src/main/scala/nl/knaw/dans/api/sword2/package.scala
> +  case class PropertiesResources(bagId: String, filePaths: List[String])
Do you mean just renaming the parameters, or also giving another type (URI)?
About the filePaths/fileUri's: I had understood that we don't give the complete file Uri's, but a path relative to the bagUri.

2016-12-07 13:43 UTC, janvanmansum commented on src/main/scala/nl/knaw/dans/api/sword2/package.scala
> +  case class PropertiesResources(bagId: String, filePaths: List[String])
Both.

About the other question: the [src](https://tools.ietf.org/html/rfc4287#section-4.1.3.2) attribute must contain an IRI, so in our case a URL.

2016-12-08 10:42 UTC, vesaakerman commented on src/main/scala/nl/knaw/dans/api/sword2/package.scala
> +  case class PropertiesResources(bagId: String, filePaths: List[String])
I looked into changing the type of the parameters from String to URL, but I am wondering if we should do it.  These values are input for org.swordapp.server.ResourcePart, where they are given as String (even though representing an IRI).  We store these values in Properties, also as Strings, and thus have to convert them when reading from or writing to Properties file. To what avail actually?  Wouldn’t it be more logical just to use the same type as in ResourcePart or in Properties, namely String?

2016-12-16 10:26 UTC, vesaakerman commented on src/main/scala/nl/knaw/dans/api/sword2/DepositHandler.scala
> +      resources <- getResources(bag)
As agreed in our discussion, I left this code in DepositHandler.  There is a check in StatementManagerImpl that takes care that the client gets to see the file uris only when the state is ARCHIVED

2016-12-21 08:59 UTC, merged